# Generated by Django 3.2.12 on 2022-03-25 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
