# Generated by Django 3.2.12 on 2022-03-27 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_rename_second_name_client_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('date_joined',), 'verbose_name': 'client', 'verbose_name_plural': 'clients'},
        ),
    ]
