# Generated by Django 3.2.12 on 2022-03-27 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_auto_20220328_0151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': 'match', 'verbose_name_plural': 'matches'},
        ),
        migrations.AlterModelTable(
            name='match',
            table='matches',
        ),
    ]
